controller:
  adminUser: admin
  adminPassword: 03102020
  serviceType: LoadBalancer
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  nodeSelector: {}
  tolerations: []
  affinity: {}
persistence:
  enabled: true
  size: 8Gi
  storageClass: "gp2"
rbac:
  create: true
