
controller:
  adminUser: "${jenkins_admin_user}"
  adminPassword: "${jenkins_admin_password}"
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - blueocean
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
persistence:
  enabled: false
