
controller:
  adminUser: admin
  adminPassword: admin123

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: false

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
