server:
  service:
    type: LoadBalancer

configs:
  cm:
    application.instanceLabelKey: argocd.argoproj.io/instance

rbac:
  policy.default: role:readonly
  policy.csv: |
    g, admin, role:admin
