apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.applications[0].name }}
  namespace: argocd
spec:
  project: {{ .Values.applications[0].project }}
  source:
    repoURL: {{ .Values.applications[0].source.repoURL }}
    targetRevision: {{ .Values.applications[0].source.targetRevision }}
    path: {{ .Values.applications[0].source.path }}
  destination:
    server: {{ .Values.applications[0].destination.server }}
    namespace: {{ .Values.applications[0].destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
